use crate::ftzrs::*;
use crate::hasfeatures::{HasFeatures, HasName};
use std::rc::Rc;
use unidecode::unidecode;

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash)]
pub(crate) struct LangRoot {
    pub(crate) id: String,
    pub(crate) native_name: String,
    pub(crate) english_name: String,
    pub(crate) unidecoded: String,
}

#[derive(Debug, Clone, PartialOrd, Ord, PartialEq, Eq, Hash)]
pub(crate) enum LangColumn {
    LangID(Rc<LangRoot>),
    EnName(Rc<LangRoot>),
    NativeName(Rc<LangRoot>),
    Unidecoded(Rc<LangRoot>),
}

impl LangColumn {
    fn root<'a>(&'a self) -> &'a Rc<LangRoot> {
        match self {
            LangColumn::LangID(s) => s,
            LangColumn::EnName(s) => s,
            LangColumn::Unidecoded(s) => s,
            LangColumn::NativeName(s) => s,
        }
    }

    pub(crate) fn from_query(s: String) -> Self {
        LangColumn::NativeName(Rc::new(LangRoot {
            id: "".to_owned(),
            native_name: prepare_str(&s),
            unidecoded: "".to_owned(),
            english_name: "".to_owned(),
        }))
    }

    fn root_column<'a>(&'a self) -> &'a String {
        match self {
            LangColumn::LangID(s) => &s.id,
            LangColumn::EnName(s) => &s.english_name,
            LangColumn::Unidecoded(s) => &s.unidecoded,
            LangColumn::NativeName(s) => &s.native_name,
        }
    }
}

impl HasFeatures for LangColumn {
    type Tok = u8;
    fn collect_features_with<F: CanGram>(&self, ftzr: &F) -> Vec<Feature> {
        let mut feats: Vec<Feature> = Vec::new();
        {
            let mut updt = |f: Feature| feats.push(f);

            match self {
                //LangColumn::NativeName(s) => {
                //    let chars: Vec<_> = Iterator::collect(s.native_name.chars());
                //    ftzr.run(&chars, &mut updt);
                //}
                otherwise => {
                    let words1 = otherwise.root_column().replace("(", "").replace(")", "");
                    let words = words1.split_ascii_whitespace();
                    for word in words {
                        ftzr.run(word.as_bytes(), &mut updt)
                    }
                }
            };
        }
        feats
    }
}

impl HasName for LangColumn {
    type Id = Rc<LangRoot>;
    fn name(&self) -> Self::Id {
        self.root().clone()
    }
}

fn prepare_str(s: &str) -> String {
    s.to_lowercase()
}

pub(crate) fn get_lang_names() -> Vec<LangColumn> {
    let lang_triplets = vec![
        ("en", "English", "English"),
        ("abx", "Abaknon", "Abaknon"),
        ("aba", "Abɛ", "Abbey"),
        ("ab", "аԥсуа", "Abkhaz"),
        ("abn", "Abua", "Abua"),
        ("abz", "Alor Abui", "Abui"),
        ("fr-x-acd", "Acadien", "Acadian"),
        ("acr", "achi", "Achi"),
        ("ach", "Acholi", "Acholi"),
        ("acu", "achuar-shiwiar", "Achuar-Shiwiar"),
        ("adh", "Dhopadhola", "Adhola"),
        ("ady", "адыгабзэ", "Adyghe"),
        ("af", "Afrikaans", "Afrikaans"),
        ("aha", "Aɣɩnda", "Ahanta"),
        ("ajg", "Aja", "Aja"),
        ("aji", "A'jië", "Ajië"),
        ("knj", "akateko", "Akateko"),
        ("ahk", "Akha", "Akha"),
        ("sq", "shqip", "Albanian"),
        ("sqk", "shqipe e shenjave", "Albanian Sign Language"),
        ("alq", "Anishinàbemowin", "Algonquin"),
        ("gsw-x-ltn", "Elsässisch", "Alsatian"),
        ("alt", "алтай", "Altai"),
        ("alz", "Alur", "Alur"),
        ("omb", "Ambae (East)", "Ambae (East)"),
        ("ase", "American Sign Language", "American Sign Language"),
        ("am", "አማርኛ", "Amharic"),
        ("ami", "阿美語", "Amis"),
        ("amu", "ñoomndaa", "Amuzgo (Guerrero)"),
        ("anm", "Anal", "Anal"),
        (
            "sgn-ao",
            "Língua angolana de sinais",
            "Angolan Sign Language",
        ),
        ("any-ci", "Anyin (Indenie)", "Anyin (Indenie)"),
        ("app", "Apma", "Apma"),
        ("ar", "العربية", "Arabic"),
        ("arq", "العربيّة (الدّارجة الجزائريّة)", "Arabic (Algeria)"),
        ("arz", "العربية (اللهجة المصرية)", "Arabic (Egypt)"),
        ("acm", "العربية (اللهجة‏ ‏العراقية)‏", "Arabic (Iraq)"),
        ("ajp", "العربية (اللهجة‏ ‏الأردنية)‏", "Arabic (Jordan)"),
        ("apc", "العربية (اللهجة اللبنانية)", "Arabic (Lebanon)"),
        ("ary", "العربية (الدارجة المغربية)", "Arabic (Morocco)"),
        ("pga", "Arabi Juba", "Arabic (Sudanese Creole)"),
        ("apd", "Arabic (Sudanese)", "Arabic (Sudanese)"),
        ("apc-sy", "العربية (اللهجة‏ السورية)‏", "Arabic (Syria)"),
        ("aeb", "العربية (الدّارجة‏ ‏التّونسيّة)", "Arabic (Tunisia)"),
        (
            "aed",
            "lengua de señas argentina",
            "Argentinean Sign Language",
        ),
        ("arh", "Arhuaco", "Arhuaco"),
        ("hy", "Հայերեն", "Armenian"),
        (
            "hy-x-krb",
            "Հայերեն (արևելյան բարբառ)",
            "Armenian (Eastern dialect)",
        ),
        ("hyw", "Արեւմտահայերէն", "Armenian (West)"),
        ("aen", "Հայերեն ժեստերի լեզու", "Armenian Sign Language"),
        ("aia", "Arosi", "Arosi"),
        ("cni", "ashaninka", "Ashaninka"),
        ("as", "অসমীয়া", "Assamese"),
        ("aii", "ܐܵܬܘܿܪܵܝܵܐ", "Assyrian"),
        (
            "cld",
            "Assyro-Chaldean (Silopi)",
            "Assyro-Chaldean (Silopi)",
        ),
        ("tay", "Tayal", "Atayal"),
        ("teo", "Ateso", "Ateso"),
        ("ati", "Akie", "Attié"),
        ("djk", "Okanisitongo", "Aukan"),
        (
            "asf",
            "Auslan (Australian Sign Language)",
            "Australian Sign Language",
        ),
        (
            "asq",
            "Österreichische Gebärdensprache",
            "Austrian Sign Language",
        ),
        ("av", "магӀарул", "Avar"),
        ("awa", "Awadhi", "Awadhi"),
        ("agr", "awajun", "Awajun"),
        ("azo", "Awing", "Awing"),
        ("nfl", "Ayiwo", "Ayiwo"),
        ("ay", "Aymara", "Aymara"),
        ("az", "Azərbaycan", "Azerbaijani"),
        ("azb", "آذربايجانى (عربى)", "Azerbaijani (Arabic)"),
        (
            "az-cyrl",
            "Aзәрбајҹан (кирил әлифбасы)",
            "Azerbaijani (Cyrillic)",
        ),
        ("wyy-x-fnb", "Ba", "Ba"),
        ("bfq", "படகா", "Badaga"),
        ("ksf", "bafia (rikpag)", "Bafia"),
        ("bkh", "Bakoko", "Bakoko"),
        ("ban", "Bali", "Balinese"),
        ("bm", "Bamanankan", "Bambara"),
        ("bax", "Shü Pamom", "Bamun"),
        ("bwi", "Baniua", "Baniwa"),
        ("bjn", "Banjar", "Banjar"),
        ("bci", "Wawle", "Baoule"),
        ("bfa", "Bari", "Bari"),
        ("bba", "Baatɔnum", "Bariba"),
        ("ba", "башҡорт", "Bashkir"),
        ("eu", "Euskara", "Basque"),
        ("bas", "Basaa (Kamerun)", "Bassa (Cameroon)"),
        ("bsq", "Ɓǎsɔ́ɔ̀ (Ɖàbíɖà)", "Bassa (Liberia)"),
        ("btd", "Pakpak", "Batak (Dairi)"),
        ("btx", "Batak (Karo)", "Batak (Karo)"),
        ("bts", "Batak (Simalungun)", "Batak (Simalungun)"),
        ("bbc", "Batak (Toba)", "Batak (Toba)"),
        ("bxa", "Bauro", "Bauro"),
        ("ron-x-bea", "Beas", "Beas"),
        (
            "sfb",
            "Langue des signes belge francophone",
            "Belgian French Sign Language",
        ),
        ("bzj", "Bileez Kriol", "Belize Kriol"),
        ("be", "беларуская", "Belorussian"),
        ("bmb", "Kibembe", "Bembe"),
        ("bn", "বাংলা", "Bengali"),
        ("bom", "Berom", "Berom"),
        ("bmm", "Betsimisaraka Avaratra", "Betsimisaraka (Northern)"),
        ("bzc", "Betsimisaraka Atsimo", "Betsimisaraka (Southern)"),
        ("bho", "भोजपुरी", "Bhojpuri"),
        ("bho-mu", "Bhojpuri (Mauritius)", "Bhojpuri (Mauritius)"),
        ("bhw", "Biak", "Biak"),
        ("bcl", "Bicol", "Bicol"),
        ("sdo", "Bidayuh (Bukar)", "Bidayuh (Bukar)"),
        ("bib", "Bɩsa", "Bisa (Lebir)"),
        ("bi", "Bislama", "Bislama"),
        ("pov", "Kriol di Gine-Bisau", "Bissau Guinean Creole"),
        ("bps", "Blaan (Sarangani)", "Blaan (Sarangani)"),
        ("bla", "Siksikáíitsi'powahsini", "Blackfoot"),
        ("bvl", "lengua de señas boliviana", "Bolivian Sign Language"),
        ("bmq", "Boomu", "Bomu"),
        ("bs", "bosanski", "Bosnian"),
        ("sgn-bw", "Botswana Sign Language", "Botswana Sign Language"),
        ("bum", "Bulu", "Boulou"),
        (
            "bzs",
            "Língua brasileira de sinais",
            "Brazilian Sign Language",
        ),
        ("bzd", "bribri", "Bribri"),
        ("bfi", "British Sign Language", "British Sign Language"),
        ("bja", "Ebudza", "Budza"),
        ("bxk", "Bukusu", "Bukusu"),
        ("bg", "български", "Bulgarian"),
        (
            "bqn",
            "български жестомимичен език",
            "Bulgarian Sign Language",
        ),
        ("bfn", "Bunak", "Bunak"),
        ("bnn", "布農語（南部）", "Bunun (South)"),
        ("bwr", "Bura", "Bura"),
        (
            "sgn-bi",
            "Langue Des Signes Burundaise",
            "Burundi Sign Language",
        ),
        ("bxr", "буряад", "Buryat"),
        ("buc", "Kibushi", "Bushi"),
        ("buf", "Bushoong", "Bushoong"),
        ("btg", "ˈBhɛtɩgbʋʋ", "Bété"),
        ("cjp", "Cabécar (Tayní)", "Cabécar (Tayní)"),
        (
            "cak-x-cqc",
            "Kaqchikel (Chimaltenango)",
            "Cakchiquel (Central)",
        ),
        ("cak", "Kaqchikel (Sololá)", "Cakchiquel (Western)"),
        ("km", "ខ្មែរ", "Cambodian"),
        ("sgn-kh", "ភាសាសញ្ញាខ្មែរ", "Cambodian Sign Language"),
        ("car-x-crb", "Kariʼnia", "Carib"),
        ("cat", "català", "Catalan"),
        ("ceb", "Cebuano", "Cebuano"),
        (
            "sgn-cf",
            "Central African Republic Sign Language",
            "Central African Republic Sign Language",
        ),
        ("esu", "Central Alaskan Yupik", "Central Alaskan Yupik"),
        ("ch", "Chamorro", "Chamorro"),
        ("tso-mz", "xiChangana (Moçambique)", "Changana (Mozambique)"),
        ("tso-zw", "Xichangana (Zimbabwe)", "Changana (Zimbabwe)"),
        ("cbk", "Chavacano", "Chavacano"),
        ("cbi", "cha'palaa", "Cha’palaa"),
        ("ce", "нохчийн", "Chechen"),
        ("arn-x-cdg", "Chedungun labquenche", "Chedungun (Coast)"),
        ("chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ", "Cherokee"),
        (
            "hne-deva",
            "छत्तीसगढ़ी (देवनागरी)",
            "Chhattisgarhi (Devanagari)",
        ),
        ("ny", "Chichewa", "Chichewa"),
        ("cgg", "Orukiga", "Chiga"),
        ("csg", "lengua de señas chilena", "Chilean Sign Language"),
        ("cfm", "Chin (Falam)", "Chin (Falam)"),
        ("cnh", "Chin (Hakha)", "Chin (Hakha)"),
        ("tcz", "Chin (Kuki)", "Chin (Kuki)"),
        ("mrh", "Chin (Mara)", "Chin (Mara)"),
        ("hlt", "Chin (Matu)", "Chin (Matu)"),
        ("ctd", "Chin (Tedim)", "Chin (Tiddim)"),
        ("czt", "Chin (Zotung)", "Chin (Zotung)"),
        ("chj", "jújmi kiʼtsa köwɨ̱", "Chinantec (Ojitlan)"),
        ("cdo", "中文（福州话）", "Chinese (Fuzhounese)"),
        ("wuu-x-chg", "中文（上海话）", "Chinese (Shanghainese)"),
        ("cmn-x-csn", "中文（四川话）", "Chinese (Sichuanese)"),
        ("wuu-x-wnz", "中文（温州话）", "Chinese (Wenzhounese)"),
        ("cmn-x-chk", "Chinese (Yunnanese)", "Chinese (Yunnanese)"),
        (
            "yue-hans",
            "中文简体（广东话）",
            "Chinese Cantonese (Simplified)",
        ),
        (
            "yue-hant",
            "中文繁體（廣東話）",
            "Chinese Cantonese (Traditional)",
        ),
        (
            "cmn-hans",
            "中文简体（普通话）",
            "Chinese Mandarin (Simplified)",
        ),
        (
            "cmn-hant",
            "中文繁體（國語）",
            "Chinese Mandarin (Traditional)",
        ),
        ("csl", "中国手语", "Chinese Sign Language"),
        ("cax", "Chiquitano", "Chiquitano"),
        ("toi", "Chitonga", "Chitonga"),
        ("tog", "Chitonga (Malawi)", "Chitonga (Malawi)"),
        ("toi-zw", "Chitonga (Zimbabwe)", "Chitonga (Zimbabwe)"),
        ("tum", "Chitumbuka", "Chitumbuka"),
        ("yao", "Chiyao", "Chiyao"),
        ("cho", "Choctaw", "Choctaw"),
        ("cjk", "Chokwe", "Chokwe"),
        ("ctu", "ch'ol", "Chol"),
        ("chd", "lataiki", "Chontal (Oaxaca)"),
        ("chf", "yokotʼan", "Chontal (Tabasco)"),
        ("cce", "Txitxopi", "Chopi"),
        ("crt", "chorote (iyojwa'ja)", "Chorote (Iyojwa'ja)"),
        ("chw", "Etxuwabo", "Chuabo"),
        ("cac", "chuj", "Chuj"),
        ("chk", "Chuuk", "Chuukese"),
        ("cv", "чӑвашла", "Chuvash"),
        ("bem", "Cibemba", "Cibemba"),
        ("mwn", "Cinamwanga", "Cinamwanga"),
        ("nya", "Cinyanja", "Cinyanja"),
        (
            "csn",
            "lengua de señas colombiana",
            "Colombian Sign Language",
        ),
        ("cfg", "Como Karim", "Como Karim"),
        ("zdj", "Shikomori (Ngazidja)", "Comorian (Ngazidja)"),
        (
            "sgn-cd",
            "Langue des signes congolaise",
            "Congolese Sign Language",
        ),
        ("crn", "cora (el nayar)", "Cora (El Nayar)"),
        ("co", "Corsu", "Corsican"),
        (
            "csr",
            "lengua de señas costarricense",
            "Costa Rican Sign Language",
        ),
        (
            "crm-x-oc",
            "Cree Omushkego (Roman)",
            "Cree Omushkego (Roman)",
        ),
        ("crk-latn", "nēhiyawēwin", "Cree Plains (Roman)"),
        ("crk-x-cys", "ᓀᐦᐃᔭᐁᐧᐃᐧᐣ", "Cree Plains (Syllabics)"),
        ("crj-latn", "Iinuuayimuwin", "Cree Southern East (Roman)"),
        ("csw-x-yc", "Ininîmowin", "Cree West Swampy (Roman)"),
        ("csw-x-ycs", "ᐃᓂᓃᒧᐏᐣ", "Cree West Swampy (Syllabics)"),
        ("cwd-x-wc", "Nîhithawîwin", "Cree Woods (Roman)"),
        ("cwd-x-wcs", "ᓀᐦᐃᖬᐁᐧᐃᐧᐣ", "Cree Woods (Syllabics)"),
        (
            "crh-x-ctc",
            "къырымтатар (кирилл)",
            "Crimean Tatar (Cyrillic)",
        ),
        ("hr", "hrvatski", "Croatian"),
        ("csq", "hrvatski znakovni jezik", "Croatian Sign Language"),
        ("csf", "lenguaje de señas cubano", "Cuban Sign Language"),
        ("cub", "Cubeo", "Cubeo"),
        ("kpc", "Curripaco", "Curripaco"),
        ("cs", "čeština", "Czech"),
        ("cse", "český znakový jazyk", "Czech Sign Language"),
        ("dga", "Dagaare", "Dagaare"),
        ("dag", "Dagbanli", "Dagbani"),
        ("dak", "Dakota", "Dakota"),
        ("naq-x-dmr", "Damara", "Damara"),
        ("ada", "Dangme", "Dangme"),
        ("da", "Dansk", "Danish"),
        ("dsl", "Dansk tegnsprog", "Danish Sign Language"),
        ("dar", "дарган", "Dargwa"),
        ("prs", "دری", "Dari"),
        ("knx", "Dayak Ahe", "Dayak Ahe"),
        ("nij", "Dayak Ngaju", "Dayak Ngaju"),
        ("xdy", "Dayak Tomun", "Dayak Tomun"),
        ("ddn", "Dendi", "Dendi"),
        ("dez", "Londengese", "Dengese"),
        ("dic", "Dida (Lakota)", "Dida (Lakota)"),
        ("os-x-dgr", "дигорон", "Digor"),
        ("din", "Dinka", "Dinka"),
        ("dyo", "Jóola", "Diola"),
        ("tbz", "Ditammari", "Ditammari"),
        ("dts", "Dɔgɔn (Tɔrɔ Sɔ)", "Dogon (Toro So)"),
        ("dua", "Douala", "Douala"),
        ("dhv", "Drehu", "Drehu"),
        ("dng", "Dungan", "Dungan"),
        ("dtp", "Dusun", "Dusun"),
        ("nl", "Nederlands", "Dutch"),
        ("nl-be", "Nederlands (België)", "Dutch (Belgium)"),
        ("nl-sr", "Nederlands (Suriname)", "Dutch (Suriname)"),
        ("dse", "Nederlandse Gebarentaal", "Dutch Sign Language"),
        ("dzo-tibt", "Dzongkha (Tibetan)", "Dzongkha (Tibetan)"),
        ("igb", "Ebira", "Ebira"),
        (
            "ecs",
            "lengua de señas ecuatoriana",
            "Ecuadorian Sign Language",
        ),
        ("bin", "Edo", "Edo"),
        ("llp", "Efate (North)", "Efate (North)"),
        ("erk", "Efate (South)", "Efate (South)"),
        ("efi", "Efịk", "Efik"),
        ("cto", "embera katio", "Emberá (Catío)"),
        ("cmi", "ẽbẽra beɗea chamí", "Emberá (Chamí)"),
        ("emp", "Emberá dóbida", "Emberá (Northern)"),
        ("enq", "Enga", "Enga"),
        ("en", "English", "English"),
        ("en-ng", "English (Nigeria)", "English (Nigeria)"),
        ("en-zm", "English (Zambia)", "English (Zambia)"),
        ("myv", "эрзянь", "Erzya"),
        ("ish", "Esan", "Esan"),
        ("et", "eesti", "Estonian"),
        ("eso", "eesti viipekeel", "Estonian Sign Language"),
        ("eth", "የኢትዮጵያ ምልክት ቋንቋ", "Ethiopian Sign Language"),
        ("eto", "Iton", "Eton"),
        ("ee", "Eʋegbe", "Ewe"),
        ("ewo", "Ewondo", "Ewondo"),
        ("fan", "Fang", "Fang"),
        ("fat", "Mfantse", "Fante"),
        ("fo", "Føroyskt", "Faroese"),
        ("ddg", "Fataluku", "Fataluku"),
        ("fmp", "Bafang", "Fe'fe'"),
        ("sgn-fj", "Fiji Sign Language", "Fiji Sign Language"),
        ("fj", "vakaViti", "Fijian"),
        ("psp", "Filipino Sign Language", "Filipino Sign Language"),
        ("fi", "suomi", "Finnish"),
        ("fse", "suomalainen viittomakieli", "Finnish Sign Language"),
        ("vgt", "Vlaamse Gebarentaal", "Flemish Sign Language"),
        ("fon", "Fɔngbe", "Fon"),
        ("gur", "Farefare", "Frafra"),
        ("fr", "Français", "French"),
        ("fr-bj", "Français (Bénin)", "French (Benin)"),
        ("fr-ca", "Français (Canada)", "French (Canada)"),
        ("fsl", "Langue des signes française", "French Sign Language"),
        ("fy", "Frysk", "Frisian"),
        ("fub", "Fulfulde (Kamerun)", "Fulfulde (Cameroon)"),
        ("ffm", "Fulfulde (Maasina)", "Fulfulde (Maasina)"),
        ("fuv", "Fulfulde (Nigerian)", "Fulfulde (Nigerian)"),
        ("fud", "Fakafutuna", "Futuna (East)"),
        ("fwa", "Fwâi", "Fwâi"),
        ("gaa", "Ga", "Ga"),
        ("gag-x-gz", "гaгaуз", "Gagauz"),
        ("gag-x-gzr", "gagauz (latin)", "Gagauz (Roman)"),
        ("gl", "Galego", "Galician"),
        ("gbm", "गढ़वाली", "Garhwali"),
        ("cab", "Garifuna", "Garifuna"),
        ("grt-x-gar", "গারো (আবেং)", "Garo (Abeng)"),
        ("gba", "Gbaya", "Gbaya"),
        ("jw-gde", "Gedeo", "Gedeo"),
        ("ka", "ქართული", "Georgian"),
        ("de", "Deutsch", "German"),
        ("gsg", "Deutsche Gebärdensprache", "German Sign Language"),
        ("gse", "Ghanaian Sign Language", "Ghanaian Sign Language"),
        ("bbj", "Bandjoun-Baham", "Ghomálá’"),
        ("nyf", "Giryama", "Giryama"),
        ("toh", "Gitonga", "Gitonga"),
        ("gog", "Cigogo", "Gogo"),
        ("gkn", "Gokana", "Gokana"),
        ("gux", "Gulmancema", "Gourmanchéma"),
        ("goa", "Goro", "Gouro"),
        ("el", "Ελληνική", "Greek"),
        ("gss", "Ελληνική Νοηματική Γλώσσα", "Greek Sign Language"),
        ("kl", "Kalaallisut", "Greenlandic"),
        ("kl-x-gle", "Tunumiisut", "Greenlandic (East)"),
        ("gcf", "Kréyòl Gwadloup", "Guadeloupean Creole"),
        ("guh", "guahibo", "Guahibo"),
        ("gum", "Namtrik", "Guambiano"),
        ("gug", "guarani", "Guarani"),
        ("gui", "Guaraní boliviano", "Guarani (Bolivia)"),
        ("gun", "Guaraní (Mbyá)", "Guaraní (Mbyá)"),
        ("gyr", "Guarayu", "Guarayu"),
        (
            "gsm",
            "lenguaje de señas guatemalteco",
            "Guatemalan Sign Language",
        ),
        ("gkp", "Kpɛlɛɛwoo", "Guerze"),
        ("gcr", "Kréyòl gwiyanè", "Guianese Creole"),
        ("gu", "ગુજરાતી", "Gujarati"),
        ("guw", "Gungbe", "Gun"),
        ("guw-bj", "Gun (Benin)", "Gun (Benin)"),
        ("cuk", "dule", "Guna"),
        ("gyn", "Guyanese Creole English", "Guyanese Creole English"),
        ("gxx", "wɛ", "Guéré"),
        ("ht", "Kreyòl ayisyen", "Haitian Creole"),
        ("hak-id", "Cina Khek (Indonesia)", "Hakka (Indonesia)"),
        ("hak", "客家話（台灣）", "Hakka (Taiwan)"),
        ("hla", "Halia", "Halia"),
        ("hyw-x-hma", "համշեներեն (հայերեն)", "Hamshen (Armenian)"),
        ("hyw-x-hms", "һамшенерен (кирилица)", "Hamshen (Cyrillic)"),
        ("lml", "Hano", "Hano"),
        ("bgc", "Haryanvi", "Haryanvi"),
        ("ha", "Hausa", "Hausa"),
        ("hav", "Ekihavu", "Havu"),
        ("haw", "ʻŌlelo Hawaiʻi", "Hawaiian"),
        ("hwc", "Hawai’i Pidgin", "Hawai’i Pidgin"),
        ("hvn", "Sabu", "Hawu"),
        ("hay", "Ekihaya", "Haya"),
        ("he", "עברית", "Hebrew"),
        ("heh", "Kihehe", "Hehe"),
        ("hz", "Otjiherero", "Herero"),
        ("hil", "Hiligaynon", "Hiligaynon"),
        ("hi", "हिंदी", "Hindi"),
        ("hif", "Hindi (Fiji)", "Hindi (Fiji)"),
        ("hi-latn", "Hindi (Roman)", "Hindi (Roman)"),
        ("ho", "Hiri Motu", "Hiri Motu"),
        ("mbn", "Jitnu", "Hitnu"),
        ("hnj", "Moob Ntsuab", "Hmong (Green)"),
        ("hmn", "Hmoob Dawb", "Hmong (White)"),
        (
            "hds",
            "lenguaje de señas hondureño",
            "Honduras Sign Language",
        ),
        ("hks", "香港手語", "Hong Kong Sign Language"),
        ("hop", "Hopi", "Hopi"),
        ("hus", "tének", "Huastec (San Luis Potosi)"),
        ("hus-x-hsv", "tének de Veracruz", "Huastec (Veracruz)"),
        ("huv", "ombeayiiüts", "Huave (San Mateo del Mar)"),
        ("hul", "Vula’a", "Hula"),
        ("hu", "magyar", "Hungarian"),
        ("hsh", "magyar jelnyelv", "Hungarian Sign Language"),
        ("hrx", "Hunsrik", "Hunsrik"),
        ("iai", "Iaai", "Iaai"),
        ("ibl", "Ibaloi", "Ibaloi"),
        ("iba", "Iban", "Iban"),
        ("ibg", "Ibanag", "Ibanag"),
        ("yom-x-ibi", "Ibinda", "Ibinda"),
        ("is", "íslenska", "Icelandic"),
        ("idu", "Idoma", "Idoma"),
        ("ifk", "Ifugao", "Ifugao"),
        ("igl", "Igala", "Igala"),
        ("ig", "Igbo", "Igbo"),
        ("ige", "Igede", "Igede"),
        ("ign", "Ignaciano", "Ignaciano"),
        ("ijc", "Ijaw", "Ijaw"),
        ("ilo", "Iloko", "Iloko"),
        ("akl", "Inakeanon", "Inakeanon"),
        ("ins", "Indian Sign Language", "Indian Sign Language"),
        ("id", "Indonesia", "Indonesian"),
        (
            "inl",
            "Bahasa Isyarat Indonesia",
            "Indonesian Sign Language",
        ),
        ("inb", "Inga", "Inga"),
        ("iu-latn", "Inuktitut", "Inuktitut (Roman)"),
        ("iu", "ᐃᓄᒃᑎᑐᑦ (ᖃᓂᐅᔮᖅᐸᐃᑦ)", "Inuktitut (Syllabics)"),
        ("ga", "Gaeilge", "Irish"),
        ("isg", "Irish Sign Language", "Irish Sign Language"),
        ("iso", "Isoko", "Isoko"),
        ("isr", "שפת סימנים ישראלית", "Israeli Sign Language"),
        ("it", "Italiano", "Italian"),
        ("ise", "Lingua dei segni italiana", "Italian Sign Language"),
        ("itv", "Itawit", "Itawit"),
        ("its", "Itsekiri", "Itsekiri"),
        ("ium", "Iu-Mienh", "Iu Mien"),
        ("ivv", "Ivatan", "Ivatan"),
        (
            "sgn-ci",
            "Langue des signes ivoirienne",
            "Ivorian Sign Language",
        ),
        ("ixl", "ixil", "Ixil"),
        ("jam-x-jcr", "Patwa", "Jamaican Creole"),
        ("jls", "Jamaican Sign Language", "Jamaican Sign Language"),
        ("ja", "日本語", "Japanese"),
        ("jsl", "日本手話", "Japanese Sign Language"),
        ("jra", "Jarai", "Jarai"),
        ("jv", "Jawa", "Javanese"),
        ("jav", "Jawa Timur", "Javanese (Eastern)"),
        ("jje", "제주어", "Jejueo"),
        ("whg", "Yuwei", "Jiwaka"),
        ("dyu", "Jula", "Jula"),
        ("kbd", "адыгэбзэ", "Kabardin-Cherkess"),
        ("kbp", "Kabɩyɛ", "Kabiye"),
        ("kea", "Kabuverdianu", "Kabuverdianu"),
        ("kab", "Taqbaylit", "Kabyle"),
        ("kac", "Kachin", "Kachin"),
        ("fij-x-kdv", "Kadavu", "Kadavu"),
        ("kzj", "Kadazan", "Kadazan"),
        ("kgp", "Kaingang", "Kaingang"),
        ("kgk", "Kaiwá", "Kaiwá"),
        ("kck-x-kl", "Kalanga (Botswana)", "Kalanga (Botswana)"),
        ("kck-x-klz", "Kalanga (Zimbabwe)", "Kalanga (Zimbabwe)"),
        ("kln", "Kalenjin", "Kalenjin"),
        ("xal", "хальмг", "Kalmyk"),
        ("kyk", "Kamayo", "Kamayo"),
        ("kam", "Kikamba", "Kamba"),
        ("xbr", "Kambera (Sumba Timur)", "Kambera"),
        ("hig", "Kamwe", "Kamwe"),
        ("xnr", "कंगड़ी (हमीरपुरी)", "Kangri (Hamirpuri)"),
        ("kne", "Kankanaey", "Kankanaey"),
        ("kn", "ಕನ್ನಡ", "Kannada"),
        ("kny", "Ciin-kanyok", "Kanyok"),
        ("kpg", "Kapingamarangi", "Kapingamarangi"),
        ("krc", "къарачай-малкъар", "Karachay-Balkar"),
        ("kaa", "қарақалпақ", "Karakalpak"),
        ("pww", "โผล่ง", "Karen (Pwo Northern)"),
        ("pwo", "Karen (Pwo Western)", "Karen (Pwo Western)"),
        ("ksw", "ကညီ(စှီၤ)ကျိာ်", "Karen (S'gaw)"),
        ("csb", "kaszëbsczi", "Kashubian"),
        ("kk", "қазақ", "Kazakh"),
        ("kk-arab", "قازاق ٴتىلى (ارابشا جازۋى)", "Kazakh (Arabic)"),
        ("kei", "Kei", "Kei"),
        ("kek", "Q’eqchi’", "Kekchi"),
        ("khy", "Lokele", "Kele"),
        ("kem", "Kemak", "Kemak"),
        ("xki", "Kenyan Sign Language", "Kenyan Sign Language"),
        ("kjh", "хакас", "Khakass"),
        ("ogo", "Khana", "Khana"),
        ("kha", "Khasi", "Khasi"),
        ("kxm", "ขแมร์เสียม", "Khmer (Northern)"),
        ("kqn", "Kikaonde", "Kikaonde"),
        ("kwy", "Kikongo", "Kikongo"),
        ("ktu-x-kgl", "Kikongo ya leta", "Kikongo ya Leta"),
        ("ki", "Gĩkũyũ", "Kikuyu"),
        ("lu", "Kiluba", "Kiluba"),
        ("kg-x-mnn", "Kimanianga", "Kimanyanga"),
        ("kmb", "Kimbundu", "Kimbundu"),
        ("nnb", "Kinande", "Kinande"),
        ("krj", "Kinaray-a", "Kinaray-a"),
        ("nyy-x-kk", "Kinyakyusa", "Kinyakyusa"),
        ("rw", "Ikinyarwanda", "Kinyarwanda"),
        ("pem", "Kipende", "Kipende"),
        ("ky", "кыргыз", "Kirghiz"),
        ("gil", "Kiribati", "Kiribati"),
        ("run", "Ikirundi", "Kirundi"),
        ("kss", "Kisiei", "Kisi"),
        ("guz", "Kisii", "Kisii"),
        ("sop", "Kisongye", "Kisonge"),
        ("ktu-x-kit", "Kituba", "Kituba"),
        ("kzn", "Kokola", "Kokola"),
        ("kpv", "коми", "Komi"),
        ("koi", "коми-пермяцкӧй", "Komi-Permyak"),
        ("kg", "Kikongo (Rép. dém. du congo)", "Kongo"),
        ("kex", "कोंकणी (देवनागरी)", "Konkani (Devanagari)"),
        ("knn", "ಕೊಂಕಣಿ (ಕನ್ನಡ)", "Konkani (Kannada)"),
        ("gom", "Konkani (Romi)", "Konkani (Roman)"),
        ("kno", "Kono", "Kono"),
        ("ko", "한국어", "Korean"),
        ("ko-cn", "조선어", "Korean (China)"),
        ("kvk", "한국 수어", "Korean Sign Language"),
        ("kos", "Kosraean", "Kosraean"),
        ("eko", "Koti", "Koti"),
        ("xpe", "Kpelle", "Kpelle"),
        ("kri", "Krio", "Krio"),
        ("tt-x-kry", "керәшен татар", "Kryashen"),
        ("ksd", "Tinata Tuna", "Kuanua"),
        ("sbs", "Kuhane (Subiya)", "Kuhane (Subiya)"),
        ("kue", "Kuman", "Kuman"),
        ("kum", "къумукъ", "Kumyk"),
        ("kun", "Kunama", "Kunama"),
        ("kmr-x-rd", "Kurdî (Kurmancî)", "Kurdish Kurmanji"),
        (
            "kmr-x-rdu",
            "Kurdî Kurmancî (Kavkazûs)",
            "Kurdish Kurmanji (Caucasus)",
        ),
        (
            "kmr-cyrl",
            "К′öрди Кöрманщи (Кирили)",
            "Kurdish Kurmanji (Cyrillic)",
        ),
        ("ckb", "کوردی سۆرانی", "Kurdish Sorani"),
        ("kuj", "Igikuria", "Kuria"),
        ("kfr", "કચ્છી", "Kutchi"),
        ("olu", "Kuvale (Mucubal)", "Kuvale (Mucubal)"),
        ("kdt", "Kuy", "Kuy"),
        ("kwd", "Kwaio", "Kwaio"),
        ("kwn", "Rukwangali", "Kwangali"),
        ("kj", "Oshikwanyama", "Kwanyama"),
        ("kwf", "Kwara'ae", "Kwara'ae"),
        ("nmg", "Kwasio", "Kwasio"),
        ("nyy-x-nkn", "Kyangonde", "Kyangonde"),
        ("lld-x-lad", "Ladin de Gherdëina", "Ladin (Gardenese)"),
        ("lhu", "Laˇhuˍ hkawˇ", "Lahu"),
        ("lbe", "лакку", "Lak"),
        ("lkt", "Lakotiya", "Lakota"),
        ("leb", "Lala-Bisa", "Lala-Bisa"),
        ("lam", "IciLamba", "Lamba"),
        ("lai", "Chilambya", "Lambya"),
        ("laj", "Lango", "Lango"),
        ("lo", "ລາວ", "Laotian"),
        ("ldi", "Kilari", "Lari"),
        ("ltg", "Latgalīšu", "Latgalian"),
        ("lv", "latviešu", "Latvian"),
        ("lsl", "latviešu zīmju valoda", "Latvian Sign Language"),
        ("llx", "Lauan", "Lauan"),
        ("sgn-lb", "لغة الاشارات اللبنانية", "Lebanese Sign Language"),
        ("lea", "Lega", "Lega"),
        ("lln", "Lele", "Lele"),
        ("tnl", "Lenakel", "Lenakel"),
        ("led", "Baledha", "Lendu"),
        ("leh", "Cilenje", "Lenje"),
        ("lez", "лезги", "Lezgian"),
        ("koo", "Lhukonzo", "Lhukonzo"),
        ("lir", "Liberian English", "Liberian English"),
        ("lia", "Limba (West-Central)", "Limba (West-Central)"),
        ("lmp", "Limbum", "Limbum"),
        ("ln", "Lingala", "Lingala"),
        ("ngc", "Lingombe", "Lingombe"),
        ("lis", "ꓡꓲ-ꓢꓴ", "Lisu"),
        ("lt", "lietuvių", "Lithuanian"),
        ("lls", "lietuvių gestų", "Lithuanian Sign Language"),
        ("log", "Logoti", "Logo"),
        ("llb", "Ilolo", "Lolo"),
        ("lom", "Lɔɔma", "Loma"),
        ("lol", "Lɔmɔngɔ", "Lomongo"),
        ("ngl", "Elomwe", "Lomwe"),
        ("lnu", "Longuda", "Longuda"),
        ("pdt", "Plautdietsch", "Low German"),
        ("lch", "Luchazi", "Luchazi"),
        ("lg", "Luganda", "Luganda"),
        ("lgg", "Lugbara", "Lugbara"),
        ("lun", "Lunda", "Lunda"),
        ("luo", "Dholuo", "Luo"),
        ("lue", "Luvale", "Luvale"),
        ("lb", "Lëtzebuergesch", "Luxembourgish"),
        ("mas", "Maasai", "Maasai"),
        ("mk", "македонски", "Macedonian"),
        ("vmw", "Emakhuwa", "Macua"),
        ("fij-x-mct", "Macuata", "Macuata"),
        ("mbc", "Makusi", "Macushi"),
        (
            "mzc",
            "Tenin’ny Tanana Malagasy",
            "Madagascar Sign Language",
        ),
        ("mhi", "Madi", "Madi"),
        ("mad", "Madura", "Madura"),
        ("mdh", "Maguindanao", "Maguindanao"),
        ("swb-x-orr", "Shimaore (Alifuɓe)", "Mahorian (Roman)"),
        ("mai", "मैथिली", "Maithili"),
        ("mcp", "Makaa", "Makaa"),
        ("mkz-x-mks", "Makasae", "Makasae"),
        ("mkz-x-mko", "Makasae (Ossu)", "Makasae (Ossu)"),
        ("xmc", "Makhuwa-Marrevone", "Makhuwa-Marrevone"),
        ("mgh", "Emakhuwa Emeetto", "Makhuwa-Meetto"),
        ("mhm", "Makhuwa-Moniga", "Makhuwa-Moniga"),
        ("vmk", "Makhuwa-Shirima", "Makhuwa-Shirima"),
        ("kde", "Shimakonde", "Makonde"),
        ("mg", "Malagasy", "Malagasy"),
        ("mln", "Malango", "Malango"),
        (
            "sgn-mw",
            "Chinenero Chamanja cha ku Malawi",
            "Malawi Sign Language",
        ),
        ("ms", "Melayu", "Malay"),
        ("pmy", "Malay (Papuan)", "Malay (Papuan)"),
        ("ml", "മലയാളം", "Malayalam"),
        ("xml", "Bahasa Isyarat Malaysia", "Malaysian Sign Language"),
        ("mt", "Malti", "Maltese"),
        ("mdl", "Lingwa tas-Sinjali Maltija", "Maltese Sign Language"),
        ("mam", "mam", "Mam"),
        ("mqj", "Mamasa", "Mamasa"),
        ("mgm-x-mma", "Mambae (Aileu)", "Mambae (Aileu)"),
        (
            "mgm-x-mms",
            "Mambae (Ainaro no Same)",
            "Mambae (Ainaro and Same)",
        ),
        ("mgm-x-mme", "Mambae (Ermera)", "Mambae (Ermera)"),
        ("mgr", "Cimambwe-Lungu", "Mambwe-Lungu"),
        ("xmm", "Manado", "Manado Malay"),
        ("mnk", "Mandinka", "Mandinka"),
        ("mfv", "Manjaku", "Mandjak"),
        ("mrv", "Mangareva", "Mangareva"),
        ("mdj", "Némangbetu", "Mangbetu"),
        ("emk", "Maninkakan", "Maninkakan (Eastern)"),
        ("mni", "মৈতৈলোন্", "Manipuri"),
        ("mni-latn", "Manipuri (Roman)", "Manipuri (Roman)"),
        ("knf", "Mankanya", "Mankanya"),
        ("mev", "Maa", "Mano"),
        ("mns", "маньси", "Mansi"),
        ("mny", "Emanyawa", "Manyawa"),
        ("mi", "Te Reo Māori", "Maori"),
        ("arn", "mapudungun", "Mapudungun"),
        ("rag", "Luragooli", "Maragoli"),
        ("mrw", "Maranaw", "Maranaw"),
        ("mr", "मराठी", "Marathi"),
        ("mhr", "марий", "Mari"),
        ("mrj", "кырык мары", "Mari (Hill)"),
        ("mqm", "Marquisien (Hiva Oa)", "Marquesian (Hiva Oa)"),
        ("mrq", "Marquisien (Nuku Hiva)", "Marquesian (Nuku Hiva)"),
        ("mh", "Kajin M̦ajel̦", "Marshallese"),
        ("gcf-x-mtc", "Kréyol Matinik", "Martiniquan Creole"),
        ("shr", "Mashi", "Mashi"),
        ("mgv", "Kimatengo", "Matengo"),
        ("mfe", "Kreol Morisien", "Mauritian Creole"),
        ("lsy", "Mauritian Sign Language", "Mauritian Sign Language"),
        ("yua", "maaya", "Maya"),
        ("mop", "T'an", "Maya (Mopán)"),
        ("yan", "mayangna", "Mayangna"),
        ("mfy", "yoremnok'ki", "Mayo"),
        ("maz", "jñatrjo", "Mazahua"),
        ("mau", "énná", "Mazatec (Huautla)"),
        ("mdp", "Gimbala", "Mbala"),
        ("mbo", "Mbo", "Mbo"),
        ("mhw", "Thimbukushu", "Mbukushu"),
        ("mck", "Mbunda", "Mbunda"),
        ("nan-x-mdh", "Hokkien Medan", "Medan Hokkien"),
        ("byv", "Bangangté", "Medumba"),
        (
            "sgn-pg",
            "Melanesian Sign Language",
            "Melanesian Sign Language",
        ),
        ("med", "Melpa", "Melpa"),
        ("men", "Mɛnde", "Mende"),
        ("mwv", "Mentawai", "Mentawai"),
        ("mer", "Kĩmĩĩrũ", "Meru"),
        ("mgo", "Meta'", "Meta'"),
        ("mfs", "lengua de señas mexicana", "Mexican Sign Language"),
        ("nan-x-chn", "闽南语（泉州）", "Min Nan (Quanzhou)"),
        ("nan-x-chw", "閩南語（台灣）", "Min Nan (Taiwan)"),
        ("xmf", "მარგალური", "Mingrelian"),
        ("miq", "miskitu", "Miskito"),
        ("mco", "ayuk", "Mixe (North Central)"),
        ("mio", "saʼan xiñi saví", "Mixtec (Costa)"),
        ("mxv", "tu’un sâví", "Mixtec (Guerrero)"),
        ("jmx", "Tu̱ʼun ndaʼví", "Mixtec (Huajuapan)"),
        ("xtd", "ñutnuu", "Mixtec (Tilantongo)"),
        ("meh", "saʼan savi", "Mixtec (Tlaxiaco)"),
        ("lus", "Mizo", "Mizo"),
        ("mic", "Mi'kmaw", "Mi’kmaq"),
        ("cmo", "Bunong", "Mnong (Central)"),
        ("mfq", "Muaba", "Moba"),
        ("moh", "Kanienʼkéha", "Mohawk"),
        ("mkj", "Mokilese", "Mokilese"),
        ("mdf", "мокшень", "Moksha"),
        ("mn", "монгол", "Mongolian"),
        ("mvf", "Mongolian (Traditional)", "Mongolian (Traditional)"),
        ("msr", "монгол дохионы хэл", "Mongolian Sign Language"),
        ("cnr", "crnogorski", "Montenegrin"),
        ("mos", "Moore", "Moore"),
        ("mgd", "Moru", "Moru"),
        ("meu", "Motu", "Motu"),
        ("mua", "Moundang", "Moundang"),
        (
            "mzy",
            "Língua de Sinais Moçambicana",
            "Mozambican Sign Language",
        ),
        ("my", "မြန်မာ", "Myanmar"),
        ("sgn-mm", "မြန်မာ လက်သင်္ကေတပြဘာသာစကား", "Myanmar Sign Language"),
        ("fij-x-ndi", "Nadi", "Nadi"),
        ("wyy-x-ndr", "Nadroga", "Nadroga"),
        ("nbu", "Naga (Rongmei)", "Naga (Rongmei)"),
        ("nag", "Nagamese", "Nagamese"),
        ("ncx", "náhuatl del centro", "Nahuatl (Central)"),
        ("ngu", "náhuatl de guerrero", "Nahuatl (Guerrero)"),
        ("nch", "náhuatl de la huasteca", "Nahuatl (Huasteca)"),
        (
            "ncj",
            "náhuatl del norte de Puebla",
            "Nahuatl (Northern Puebla)",
        ),
        ("nhk", "náhuatl de Veracruz", "Nahuatl (Veracruz)"),
        ("naq-x-na", "ǀApakhoen gowab", "Nama"),
        ("nmk", "Namakura", "Namakura"),
        ("nmq", "Nambya", "Nambya"),
        ("nbs", "Namibian Sign Language", "Namibian Sign Language"),
        ("bwb", "Namosi-Naitasiri-Serua", "Namosi-Naitasiri-Serua"),
        ("ncb", "Nancowry", "Nancowry"),
        ("ntu", "Natügu", "Natügu"),
        ("nxa", "Nauete", "Nauete"),
        ("na", "Nauruan", "Nauruan"),
        ("nv", "Diné Bizaad", "Navajo"),
        ("ndh", "Ichindali", "Ndali"),
        ("ndc", "Cindau", "Ndau"),
        ("nr", "IsiNdebele", "Ndebele"),
        ("nd", "Ndebele (Zimbabwe)", "Ndebele (Zimbabwe)"),
        ("ng", "Oshindonga", "Ndonga"),
        ("yrk", "ненэцяʼ", "Nenets"),
        ("yrk-x-nnf", "нешаӈ", "Nenets (Forest)"),
        ("nen", "Nengone", "Nengone"),
        ("ne", "नेपाली", "Nepali"),
        ("nsp", "नेपाली साङ्केतिक भाषा", "Nepali Sign Language"),
        (
            "nzs",
            "New Zealand Sign Language",
            "New Zealand Sign Language",
        ),
        ("new", "नेवारी", "Newari"),
        ("gym", "ngäbere", "Ngabere"),
        ("sba", "Ngambay", "Ngambaye"),
        ("nba", "Ngangela", "Ngangela"),
        ("nga", "Ngbaka", "Ngbaka"),
        ("ngb", "Ngbandi (ya Nɔrdi)", "Ngbandi (Northern)"),
        ("nnh", "Ngiemboon", "Ngiemboon"),
        (
            "pls",
            "ngigua de San Marcos Tlacoyalco",
            "Ngigua (San Marcos Tlacoyalco)",
        ),
        ("nla", "Babadjou", "Ngombale"),
        ("yrl", "Nheengatu", "Nhengatu"),
        ("nia", "Nias", "Nias"),
        (
            "ncs",
            "lenguaje de señas nicaragüense",
            "Nicaraguan Sign Language",
        ),
        ("caq", "Nicobarese", "Nicobarese"),
        ("pcm", "Nigerian Pidgin", "Nigerian Pidgin"),
        ("nsi", "Nigerian Sign Language", "Nigerian Sign Language"),
        ("niu", "Faka-Niue", "Niuean"),
        ("cag", "nivaĉle", "Nivaclé"),
        ("nzb", "Njebi", "Njebi"),
        ("nka", "Nkoya", "Nkoya"),
        ("ojb-x-nor", "Anishinaabemowin", "Northern Ojibwe (Roman)"),
        ("ojb-x-nos", "ᐊᓂᔑᓈᐯᒧᐎᓐ", "Northern Ojibwe (Syllabics)"),
        ("no", "Norsk", "Norwegian"),
        ("nsl", "Norsk tegnspråk", "Norwegian Sign Language"),
        ("nse-mz", "Chinsenga (Mozambique)", "Nsenga (Mozambique)"),
        ("nse", "Cinsenga", "Nsenga (Zambia)"),
        ("nus", "Thok Nath", "Nuer"),
        ("nuq", "Nukumanu", "Nukumanu"),
        ("nkr", "Nukuoro", "Nukuoro"),
        ("kdk", "Kwényï", "Numèè (Kwenyii)"),
        ("nyk", "Nyaneka", "Nyaneka"),
        ("nih", "Nyiha", "Nyiha"),
        ("nyu", "Cinyungwe", "Nyungwe"),
        ("nzi", "Nzema", "Nzema"),
        ("ann", "Obolo", "Obolo"),
        ("otw", "Nishnaabemwin", "Odawa"),
        ("or", "ଓଡ଼ିଆ", "Odia"),
        ("oke", "Okpe", "Okpe"),
        ("nyd", "Olunyole", "Olunyole"),
        ("mbm", "Ombamba", "Ombamba"),
        ("okv", "Orokaiva", "Orokaiva"),
        ("om", "Afaan Oromoo", "Oromo"),
        ("os", "ирон", "Ossetian"),
        ("os-x-osc", "Ирон (чысайнаг)", "Ossetian (Chsan)"),
        ("os-x-osk", "Ирон (къуыдайраг)", "Ossetian (Kudar)"),
        ("tll", "Ɔtɛtɛla", "Otetela"),
        ("otm", "ñuhü", "Otomi (Eastern Highland)"),
        ("ote", "Ñañu", "Otomi (Mezquital Valley)"),
        ("ots", "ñätho", "Otomi (State of Mexico)"),
        ("blk", "Pa'o", "Pa'o"),
        ("pma", "Paama", "Paama"),
        ("pri", "Paicî", "Paicî"),
        ("pwn", "Payuan", "Paiwan"),
        ("pau", "Palauan", "Palauan"),
        ("plu", "Palikur", "Palikúr"),
        ("pmf", "Pamona", "Pamona"),
        (
            "lsp",
            "lenguaje de señas panameño",
            "Panamanian Sign Language",
        ),
        ("pag", "Pangasinan", "Pangasinan"),
        ("pbo", "Oium", "Papel"),
        ("pap-x-paa", "Papiamento (Aruba)", "Papiamento (Aruba)"),
        ("pap", "Papiamentu (Kòrsou)", "Papiamento (Curaçao)"),
        (
            "pys",
            "lengua de señas paraguaya",
            "Paraguayan Sign Language",
        ),
        ("ps", "پښتو", "Pashto"),
        ("arn-x-phn", "chedungun (pewenche)", "Pehuenche"),
        ("aoc", "pemon pe", "Pemon"),
        ("pdc", "Pennsylvania Dutch (Deitsh)", "Pennsylvania German"),
        ("fa", "فارسی", "Persian"),
        ("prl", "lenguaje de señas peruano", "Peruvian Sign Language"),
        ("phm", "Chiphimbi", "Phimbi"),
        ("pht", "ภูไท", "Phu Thai"),
        ("pid", "huo̧ttö̧ja̧", "Piaroa"),
        ("wes", "Pidgin for Cameroon", "Pidgin (Cameroon)"),
        ("wes-x-pgw", "Pidgin (West Africa)", "Pidgin (West Africa)"),
        ("plg", "pilagá", "Pilagá"),
        ("pjt", "Pitjantjatjara", "Pitjantjatjara"),
        ("pl", "polski", "Polish"),
        ("pso", "polski język migowy", "Polish Sign Language"),
        ("nds", "Pomerisch", "Pomeranian"),
        ("pon", "Ponapean", "Ponapean"),
        ("poi", "popoluca de la Sierra", "Popoluca (Highland)"),
        ("jac-x-jc", "poptí", "Popti'"),
        ("poh", "poqomchi'", "Poqomchi'"),
        ("pt", "Português (Brasil)", "Portuguese (Brazil)"),
        ("pt-mz", "Português (Moçambique)", "Portuguese (Mozambique)"),
        ("pt-pt", "Português (Portugal)", "Portuguese (Portugal)"),
        (
            "psr",
            "Língua Gestual Portuguesa",
            "Portuguese Sign Language",
        ),
        ("fuf", "Pular", "Pular"),
        ("pa", "ਪੰਜਾਬੀ", "Punjabi"),
        ("pa-latn", "Punjabi (Roman)", "Punjabi (Roman)"),
        ("pnb", "پنجابی (شاہ مُکھی)", "Punjabi (Shahmukhi)"),
        ("puu", "Punu", "Punu"),
        ("pyu", "Pinuyumayan", "Puyuma"),
        ("pbb", "nasa yuwe", "Páez"),
        ("kjb", "q'anjob'al", "Q'anjob'al"),
        (
            "fcs",
            "Langue des signes québécoise",
            "Quebec Sign Language",
        ),
        ("que", "Quechua (Ancash)", "Quechua (Ancash)"),
        ("quy", "Quechua (Ayacucho)", "Quechua (Ayacucho)"),
        ("qu", "Quechua (Bolivia)", "Quechua (Bolivia)"),
        ("quz", "quechua (Cusco)", "Quechua (Cuzco)"),
        (
            "qub",
            "Quechua de Huánuco (Huallaga)",
            "Quechua (Huallaga Huánuco)",
        ),
        ("qvw", "quechua wanca", "Quechua (Huaylla Wanca)"),
        ("quf", "quechua (lambayeque)", "Quechua (Lambayeque)"),
        ("quc", "quiché", "Quiche"),
        ("qxr", "quichua (cañar)", "Quichua (Cañar)"),
        ("qu-x-qib", "quichua (chibuleo)", "Quichua (Chibuleo)"),
        ("qug", "quichua (chimborazo)", "Quichua (Chimborazo)"),
        ("qug-x-qix", "quichua (cotopaxi)", "Quichua (Cotopaxi)"),
        ("qvi", "quichua (imbabura)", "Quichua (Imbabura)"),
        ("qvz", "quichua (pastaza)", "Quichua (Pastaza)"),
        ("qu-x-qxl", "quichua (salasaca)", "Quichua (Salasaca)"),
        (
            "qus",
            "quichua (Santiago del Estero)",
            "Quichua (Santiago del Estero)",
        ),
        ("quw", "quichua (tena)", "Quichua (Tena)"),
        ("fij-x-fnr", "Ra", "Ra"),
        ("rap", "rapa nui", "Rapa Nui"),
        ("rar", "Reo Rarotonga", "Rarotongan"),
        ("ro", "Română", "Romanian"),
        ("ro-x-rnn", "rumunski (vlaški)", "Romanian (Vlach)"),
        (
            "ro-x-rnk",
            "rumunski (vlaški, Bačka)",
            "Romanian (Vlach, Bačka)",
        ),
        (
            "rms",
            "Limbajul semnelor românesc",
            "Romanian Sign Language",
        ),
        ("rm-x-rh", "Rumantsch (Ladin)", "Romansh (Ladin)"),
        ("rm-x-rhs", "romontsch (sursilvan)", "Romansh (Sursilvan)"),
        ("rmy-al", "rome (shqipëri)", "Romany (Albania)"),
        ("rmy-ar", "Romanes Kalderash", "Romany (Argentina)"),
        ("rmn-x-rmb", "романи (България)", "Romany (Bulgaria)"),
        ("rmy-cl", "Romane Jorajane", "Romany (Chile)"),
        ("rmn-x-rnc", "Романи (крымски)", "Romany (Crimea)"),
        (
            "rmc-sk",
            "romanes (vichodno Slovačiko)",
            "Romany (Eastern Slovakia)",
        ),
        ("rmo", "Romanes (Sinti)", "Romany (Germany)"),
        (
            "rmy-x-rmk",
            "хомани (котлярско, Хусыя)",
            "Romany (Kalderash, Russia)",
        ),
        (
            "rmy-x-rvk",
            "Романі (ловарі, чокещі)",
            "Romany (Lovari, Chokeshi)",
        ),
        (
            "rmy-x-lva",
            "romani (lovári, Ungriko Them)",
            "Romany (Lovari, Hungary)",
        ),
        ("rmn-x-rm", "romane (Makedonija)", "Romany (Macedonia)"),
        (
            "rmn-cyrl",
            "романе (Македонија) кирилица",
            "Romany (Macedonia) Cyrillic",
        ),
        (
            "rmy-x-rvc",
            "Романи (Молдова) кирилик",
            "Romany (Moldova) Cyrillic",
        ),
        (
            "rmn-x-rmn",
            "Ρομανί (Βόρεια Ελλάδα)",
            "Romany (Northern Greece)",
        ),
        ("rml-ru", "романы (русска рома)", "Romany (Northern Russia)"),
        ("rml", "romani (Polska Roma)", "Romany (Poland)"),
        ("rmy", "Rromani (România)", "Romany (Romania)"),
        ("rmn-x-rme", "Romane (Srbija)", "Romany (Serbia)"),
        (
            "rmn-x-rmg",
            "Ρομανί (Νότια Ελλάδα)",
            "Romany (Southern Greece)",
        ),
        ("rmy-ua", "Романі (ромунгри, Україна)", "Romany (Ukraine)"),
        (
            "rmy-x-rmv",
            "романи (влахитско, Россия)",
            "Romany (Vlax, Russia)",
        ),
        ("rng", "Xironga", "Ronga"),
        ("rtm", "Rotuạm ta", "Rotuman"),
        ("rug", "Roviana", "Roviana"),
        ("dru", "Drekay", "Rukai"),
        ("diu", "Rumanyo", "Rumanyo"),
        ("drg", "Momogun", "Rungus"),
        ("nyn", "Runyankore", "Runyankore"),
        ("ru", "русский", "Russian"),
        ("rsl", "русский жестовый", "Russian Sign Language"),
        ("rue", "Закарпатська русинська", "Rusyn (Carpathian)"),
        ("ttj", "Rutoro", "Rutoro"),
        (
            "sgn-rw",
            "Ururimi rw'amarenga yo mu Rwanda",
            "Rwandan Sign Language",
        ),
        ("rcf", "Kréol Rénioné", "Réunion Creole"),
        ("se", "sámegiella (davvi)", "Saami (North)"),
        ("sck-deva", "सादरी (देवनागरी)", "Sadri (Devanagari)"),
        ("acf", "Kwéyòl (Patwa)", "Saint Lucian Creole"),
        ("skg-x-skl", "Sakalava", "Sakalava"),
        ("loe", "Saluan", "Saluan"),
        (
            "esn",
            "lengua de señas salvadoreña",
            "Salvadoran Sign Language",
        ),
        ("saq", "Sampur", "Samburu"),
        ("sm", "Faa-Samoa", "Samoan"),
        ("sgn-ws", "Samoan Sign Language", "Samoan Sign Language"),
        ("sng", "Kisanga", "Sanga"),
        ("sxn", "Sangir", "Sangir"),
        ("sg", "Sango", "Sango"),
        ("sat-deva", "Santhali (Devanagari)", "Santhali (Devanagari)"),
        ("sat", "Santhali (Roman)", "Santhali (Roman)"),
        ("mwm", "Sar", "Sar"),
        ("srm", "Saamakatöngö", "Saramaccan"),
        ("hns", "Sarnami Hindoestani", "Sarnami"),
        ("sas", "Sasak", "Sasak"),
        ("mav", "Saterê-Mauê", "Sateré-Mawé"),
        ("gd", "Gàidhlig", "Scottish Gaelic"),
        ("trv-x-sdq", "Seediq", "Seediq"),
        ("sfw", "Sehwi", "Sehwi"),
        ("seh", "Cisena", "Sena"),
        ("sef", "Senarì", "Senoufo (Cebaara)"),
        ("nso", "Sepedi", "Sepedi"),
        ("nso-x-spl", "Sepulana", "Sepulana"),
        ("sr-cyrl", "српски (ћирилица)", "Serbian (Cyrillic)"),
        ("sr-latn", "srpski (latinica)", "Serbian (Roman)"),
        ("sgn-rs", "srpski znakovni jezik", "Serbian Sign Language"),
        ("srr", "Seereer", "Serer"),
        ("st", "Sesotho (Lesotho)", "Sesotho (Lesotho)"),
        ("st-za", "Sesotho (South Africa)", "Sesotho (South Africa)"),
        ("tn", "Setswana", "Setswana"),
        ("crs", "Kreol Seselwa", "Seychelles Creole"),
        ("shn", "Shan", "Shan"),
        ("cbt", "shawi", "Shawi"),
        ("shp", "shipibo-conibo", "Shipibo-Conibo"),
        ("sn", "Shona", "Shona"),
        ("jiv", "shuar", "Shuar"),
        ("sgh", "шуғнонӣ", "Shughni"),
        ("sid", "Sidaamu Afoo", "Sidama"),
        ("szl", "cieszyński", "Silesian"),
        ("loz", "Silozi", "Silozi"),
        ("sd", "سِنڌي", "Sindhi (Arabic)"),
        ("sd-deva", "Sindhi (Devanagari)", "Sindhi (Devanagari)"),
        ("snd-x-ndn", "Sindhi (Indonesia)", "Sindhi (Indonesia)"),
        ("sls", "Singapore Sign Language", "Singapore Sign Language"),
        ("si", "සිංහල", "Sinhala"),
        ("sk", "slovenčina", "Slovak"),
        ("svk", "slovenský posunkový jazyk", "Slovak Sign Language"),
        ("sl", "slovenščina", "Slovenian"),
        (
            "sgn-si",
            "slovenski znakovni jezik",
            "Slovenian Sign Language",
        ),
        ("sby", "Cisoli", "Soli"),
        ("pis", "Solomon Islands Pidgin", "Solomon Islands Pidgin"),
        ("so", "Soomaali", "Somali"),
        ("nsx", "Songo", "Songo"),
        ("soe", "Losongomino", "Songomeno"),
        ("snk", "Soninke", "Soninke"),
        (
            "sfs",
            "South African Sign Language",
            "South African Sign Language",
        ),
        ("es", "español", "Spanish"),
        ("es-es", "español (de España)", "Spanish (Spain)"),
        ("ssp", "lengua de signos española", "Spanish Sign Language"),
        ("srn", "Sranantongo", "Sranantongo"),
        ("sqs", "ශ්‍රී ලංකා සංඥා භාෂාව", "Sri Lankan Sign Language"),
        ("suk", "Kisukuma", "Sukuma"),
        ("su", "Sunda", "Sunda"),
        ("sgd", "Surigaonon", "Surigaonon"),
        ("sgn-sr", "Surinaamse Gebarentaal", "Suriname Sign Language"),
        ("sus", "Soso xui", "Susu"),
        ("sva-x-svl", "ჩუბე ლუშვანუ", "Svan (Lower)"),
        ("sva-x-svn", "ჟიბე ლუშნუ", "Svan (Upper)"),
        ("sw", "Kiswahili", "Swahili"),
        ("swc", "Kiswahili (Congo)", "Swahili (Congo)"),
        ("ss", "SiSwati", "Swati"),
        ("sgn-sz", "Swazi Sign Language", "Swazi Sign Language"),
        ("sv", "Svenska", "Swedish"),
        ("swl", "Svenskt teckenspråk", "Swedish Sign Language"),
        ("gsw", "Schweizerdeutsch", "Swiss German"),
        (
            "sgg",
            "Deutschschweizer Gebärdensprache",
            "Swiss German Sign Language",
        ),
        ("syl-x-syl", "সেলেটি (বাংলা)", "Sylheti (Bengali)"),
        ("cri", "Santome", "Sãotomense"),
        ("tap", "Taabwa", "Taabwa"),
        ("tab", "табасаран", "Tabasaran"),
        ("tl", "Tagalog", "Tagalog"),
        ("ty", "Tahiti", "Tahitian"),
        ("uar", "Tairuma", "Tairuma"),
        ("dav", "Kidawida", "Taita"),
        ("tss", "台灣手語", "Taiwanese Sign Language"),
        ("tg", "тоҷикӣ", "Tajiki"),
        ("tg-uz", "тоҷикӣ (Самарқанд)", "Tajiki (Samarkand)"),
        ("vec", "Talian", "Talian"),
        ("tly-x-tly", "Toloş", "Talysh"),
        ("tly-x-tyc", "Толош (кирил әлифба)", "Talysh (Cyrillic)"),
        ("tzm", "Tamazight", "Tamazight"),
        ("ta", "தமிழ்", "Tamil"),
        ("ta-x-tlr", "Thamil (Rōman)", "Tamil (Roman)"),
        ("tdx", "Tandroy", "Tandroy"),
        ("nmf", "Tangkhul", "Tangkhul"),
        ("xmv", "Tankarana", "Tankarana"),
        (
            "tza",
            "Lugha ya Alama ya Tanzania",
            "Tanzanian Sign Language",
        ),
        ("tar", "ralámuli", "Tarahumara (Central)"),
        ("tac", "tarahumara occidental", "Tarahumara (Western)"),
        ("tsz", "Purépecha", "Tarascan"),
        ("yer", "Tarok", "Tarok"),
        ("trv-x-trk", "Truku", "Taroko"),
        ("ttt-x-ttr", "Tat (Roman)", "Tat (Roman)"),
        ("tt", "татар", "Tatar"),
        ("tsg", "Tausug", "Tausug"),
        (
            "nzu",
            "Teke (Congo Brazzaville)",
            "Teke (Congo Brazzaville)",
        ),
        ("tek", "Kiteke (Congo Kinshasa)", "Teke (Congo Kinshasa)"),
        ("te", "తెలుగు", "Telugu"),
        ("kdh", "Kotokoli", "Tem"),
        ("nan-x-chd", "潮州", "Teochew"),
        ("nan-x-twd", "Teochew (Indonesia)", "Teochew (Indonesia)"),
        ("ter", "Terêna", "Terêna"),
        ("tet", "Tetun Belu", "Tetun Belu"),
        ("tdt", "Tetun Dili", "Tetun Dili"),
        ("twx", "Ciutee", "Tewe"),
        ("th", "ไทย", "Thai"),
        ("th-x-sik", "ไทย (โคราช)", "Thai (Korat)"),
        ("tts", "อีสาน", "Thai (Northeastern)"),
        ("nod", "กำเมือง", "Thai (Northern)"),
        ("sou", "ไทย (ใต้)", "Thai (Southern)"),
        ("tsq", "ภาษามือไทย", "Thai Sign Language"),
        ("soa", "ไทยซ้ง", "Thai Song"),
        ("tem", "Themne", "Themne"),
        ("bo", "བོད་སྐད།", "Tibetan"),
        ("tca", "Ticuna", "Ticuna"),
        ("ti", "ትግርኛ", "Tigrinya"),
        ("txq", "Rote Tii", "Tii"),
        ("tiv", "Tiv", "Tiv"),
        ("tcf", "me̱ʼpha̱a̱", "Tlapanec"),
        ("mlu", "Toabaita", "To'abaita"),
        ("tqo", "Toaripi", "Toaripi"),
        ("tob", "toba", "Toba"),
        ("toj", "tojol-abʼal", "Tojolabal"),
        ("tpi", "Tok Pisin", "Tok Pisin"),
        ("tkl", "Faka-Tokelau", "Tokelauan"),
        ("to", "Faka-Tonga", "Tongan"),
        ("sda", "Toraja", "Toraja"),
        ("tcs", "Tores Streit Kriol", "Torres Strait Creole"),
        ("top", "totonaco", "Totonac"),
        ("tui", "Toupouri", "Toupouri"),
        (
            "lst",
            "Trinidad and Tobago Sign Language",
            "Trinidad and Tobago Sign Language",
        ),
        ("lua", "Tshiluba", "Tshiluba"),
        ("tsc", "ciTshwa", "Tshwa"),
        ("cas", "Tsimané", "Tsimané"),
        ("ts", "Xitsonga", "Tsonga"),
        ("tuo", "Dahse ye", "Tucano"),
        ("tcy", "Tulu", "Tulu"),
        ("tvu", "Banen", "Tunen"),
        ("tuv", "Ng'aturkana", "Turkana"),
        ("tr", "Türkçe", "Turkish"),
        ("tr-cryl", "Тюркче (Кирил Алфабеси)", "Turkish (Cyrillic)"),
        ("tur-x-tkm", "ахыска", "Turkish (Meskhetian)"),
        ("tsm", "Türk İşaret Dili", "Turkish Sign Language"),
        ("tk", "türkmen", "Turkmen"),
        ("tk-cyrl", "түркмен (кириллица)", "Turkmen (Cyrillic)"),
        ("tvl", "Tuvalu", "Tuvaluan"),
        ("tyv", "тыва", "Tuvinian"),
        ("tw", "Twi", "Twi"),
        ("tw-x-twk", "Twi (Akuapem)", "Twi (Akuapem)"),
        ("tw-x-tws", "Twi (Asante)", "Twi (Asante)"),
        ("car-x-tyw", "Tilewuyu", "Tyrewuju"),
        ("tzh", "tseltal", "Tzeltal"),
        ("tzo", "tsotsil", "Tzotzil"),
        ("tzj", "tzʼutujil", "Tzutujil"),
        ("aoz", "Timor Dawan", "Uab Meto"),
        ("udm", "удмурт", "Udmurt"),
        ("ugn", "Ugandan Sign Language", "Ugandan Sign Language"),
        ("ug-x-uga", "ئۇيغۇر تىلى ‏(‏ئەرەب يېزىقى‏)‏‏‏‏", "Uighur (Arabic)"),
        ("ug-cyrl", "Уйғур (кирилл йезиғи)", "Uighur (Cyrillic)"),
        ("uk", "українська", "Ukrainian"),
        ("umb", "Umbundu", "Umbundu"),
        ("ur", "اُردو", "Urdu"),
        ("urh", "Urhobo", "Urhobo"),
        ("upv", "Uripiv", "Uripiv"),
        ("ugy", "lengua de señas uruguaya", "Uruguayan Sign Language"),
        ("rnd", "Uruund", "Uruund"),
        ("uz-cyrl", "ўзбекча", "Uzbek"),
        ("uzn-x-uzh", "ўзбекча (хоразм шеваси)", "Uzbek (Horezm)"),
        ("uz-latn", "o‘zbekcha (lotincha)", "Uzbek (Roman)"),
        ("ca-x-vlc", "valencià", "Valencian"),
        ("ve", "Luvenda", "Venda"),
        (
            "vsl",
            "lengua de señas venezolana",
            "Venezuelan Sign Language",
        ),
        ("skg-x-vz", "Vezo", "Vezo"),
        ("vi", "Việt", "Vietnamese"),
        (
            "hab",
            "Việt Nam (Ngôn ngữ ký hiệu)",
            "Vietnamese Sign Language",
        ),
        ("vro", "võro", "Voru"),
        ("prk", "Vax", "Wa"),
        ("wwa", "Waama", "Waama"),
        ("rob", "Waima", "Waima"),
        ("wmh", "Waimoa", "Waimoa"),
        ("wls", "Faka'uvea", "Wallisian"),
        ("lwg", "Kiwanga", "Wanga"),
        ("wap", "Wapichana", "Wapishana"),
        ("wba", "warao", "Warao"),
        ("war", "Waray-Waray", "Waray-Waray"),
        ("guc", "Wayuunaiki", "Wayuunaiki"),
        ("wew", "Wejewa (Sumba Barat)", "Wejewa"),
        ("cy", "Cymraeg", "Welsh"),
        ("wlv", "wichi", "Wichi"),
        ("hch", "wixárika", "Wixárika"),
        ("wal", "Wolayttattuwaa", "Wolaita"),
        ("wo", "Wolof", "Wolof"),
        ("xav", "A'uwẽ mreme", "Xavante"),
        ("xh", "IsiXhosa", "Xhosa"),
        ("ane", "Xârâcùù", "Xârâcùù"),
        ("daf", "Yaoba", "Yacouba"),
        ("yaf", "Iyaka", "Yaka"),
        ("sah", "сахалыы", "Yakutsk"),
        ("yas", "Yambassa", "Yambassa"),
        ("tao", "Yami", "Yami"),
        ("yns", "Iyanzi", "Yansi"),
        ("yap", "Waab", "Yapese"),
        ("yaq", "jiiak noki", "Yaqui"),
        ("ybb", "Dschang", "Yemba"),
        ("yom-x-ymb", "Kiyombe", "Yombe"),
        ("yno", "Yong", "Yong"),
        ("yo", "Yorùbá", "Yoruba"),
        ("nua", "Yuanga", "Yuanga"),
        ("yup", "yukpa", "Yukpa"),
        ("zsl", "Zambian Sign Language", "Zambian Sign Language"),
        ("zne", "Zande", "Zande"),
        ("zpg", "dîdzrie’", "Zapotec (Guevea)"),
        ("zai", "diidxazá", "Zapotec (Isthmus)"),
        ("zpd", "Dillexhon", "Zapotec (Ixtlán)"),
        ("zpa", "diitza", "Zapotec (Lachiguiri)"),
        ("ztp", "diʼste Loxich", "Zapotec (Loxicha)"),
        ("zpf", "zapoteco de Quiatoni", "Zapotec (Quiatoni)"),
        ("zpj", "ditz zea", "Zapotec (Quiavicuzas)"),
        ("zav", "didza xhidza", "Zapotec (Villa Alta)"),
        ("zab", "ditsa", "Zapotec (del Valle)"),
        ("dje", "Zarma", "Zarma"),
        ("kiu", "Zazaca (Kuzey)", "Zazaki (Northern)"),
        ("zib", "Zimbabwe Sign Language", "Zimbabwe Sign Language"),
        ("zu", "IsiZulu", "Zulu"),
    ];
    let mut out = Vec::with_capacity(lang_triplets.len() * 4);
    for (id, native, en) in lang_triplets.into_iter() {
        let lang_root = Rc::new(LangRoot {
            id: prepare_str(id),
            native_name: prepare_str(native),
            english_name: prepare_str(en),
            unidecoded: prepare_str(&unidecode(&native)),
        });
        out.push(LangColumn::EnName(lang_root.clone()));
        out.push(LangColumn::LangID(lang_root.clone()));
        out.push(LangColumn::NativeName(lang_root.clone()));
        if lang_root.english_name != lang_root.unidecoded
            && lang_root.native_name != lang_root.unidecoded
        {
            out.push(LangColumn::Unidecoded(lang_root.clone()));
        }
    }
    out
}
